import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/shared components/navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/context/theme-provider";

const DMSans = DM_Sans({ subsets: ["latin-ext"], weight: "400" });

export const metadata: Metadata = {
  title: "Data Vidya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${DMSans.className} `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="background_light-white_dark-black">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
